### ISSUE TITLE
Release for ARM

### ISSUE THREAD

**Issue by scottyeager** [threefoldtecharchive/farmerbot#11]
A few farmers have asked about running `farmerbot` on a Raspberry Pi. Because rpi uses an arm architecture, this would require releasing a set of containers built for arm. I did some initial testing, and these are my findings:

- Farmerbot - successfully compiled in an emulated arm64 container. Probably this could cross compile too
- RMB Peer - successfully cross compiled using [rust-musl-cross](https://github.com/rust-cross/rust-musl-cross)
- Grid3 Client TS - is interpreted so, no need to compile. Installs okay, didn't test functionality
- Redis - this container is already released for arm64, so nothing to do except specify the correct version

**Comment by scottyeager** [comment]
After some more research, I found that it's best to target 32 bit ARM for compatibility across generations of Raspberry Pi. Even many of the later devices which are 64 bit capable still run a 32 bit OS, and the 32 bit binaries will run without any hassle on a 64 bit OS.

To support every Pi, one can target `armv6` or `armv6hf`. In practice, it's a bit simpler to target `armv7`, aka `armhf`, which is supported by every Pi except the 1 and Zero. Nobody so far has expressed interest in using those models, so this is okay for now.

Alongside cross compiling, it's also possible to run containers in an emulated environment with QEMU in Docker. I found this necessary because one of the dependencies of `rmb-rs` does not support building for 32 bit ARM. Likewise, it's not possible to simply emulate all containers, because `grid3_client_ts` does not run in the emulator. Here's the summary of findings:

| | Emulate | Cross Compile | Native Container Upstream |
| ---| --- | --- | --- |
| `farmerbot` | Yes | Yes | – |
| `grid3_client` | No | Yes | – |
| `rmb-peer` | Yes | arm64 only | – |
| `redis` | – | – | Yes |

Since `farmerbot` itself appears to run fine under emulation (I only tested this superficially), it's not strictly necessary to provide a native container to support the Pi. However, I managed to build one anyway, and this could be added to our automated build process without much trouble.

Here's the Dockerfile:

```
FROM --platform=amd64 ubuntu:20.04 AS build

RUN apt-get update && \
    apt-get install -y \
    build-essential gcc-arm-linux-gnueabihf git

WORKDIR /opt/vlang
RUN git clone https://github.com/vlang/v /opt/vlang 
RUN make
RUN ./v symlink
RUN v -version

WORKDIR /baobab
RUN git clone -b development https://github.com/freeflowuniverse/baobab.git .
RUN bash install.sh

WORKDIR /crystallib
RUN git clone -b development https://github.com/freeflowuniverse/crystallib.git .
RUN bash install.sh

WORKDIR /farmerbot
RUN git clone https://github.com/threefoldtech/farmerbot.git /farmerbot
RUN git checkout v0.1.0-rc13
RUN bash install.sh
RUN v -prod -cc arm-linux-gnueabihf-gcc main.v

# ===== SECOND STAGE ======

FROM  ubuntu:20.04
LABEL maintainer="brandon@threefold.tech"
LABEL description="This is the 2nd stage: a very small image where we copy the farmerbot binary."

COPY --from=build /farmerbot/main /usr/local/bin/farmerbot

RUN apt-get update && apt-get install -y curl ca-certificates libatomic1

# checks
RUN ldd /usr/local/bin/farmerbot && /usr/local/bin/farmerbot --version

# Shrinking
RUN rm -rf /usr/lib/python* && \
	rm -rf /src && \
	rm -rf /usr/share/man

VOLUME ["/farmerbot"]

ENTRYPOINT ["/usr/local/bin/farmerbot"]
```

Then passing `--platform=armhf` to the `docker build` command chooses the correct platform for the second stage image. There should also be a way to do this with the Github build system.

As for `grid3_client_ts`, it wasn't as simple as I first thought. There are some dependency libraries that use native executables which must be compiled. However, this was still pretty straightforward, building inside an emulated environment this time. I'll open a separate issue on that repository to request adding the arm build to the process there.

**Comment by brandonpille** [comment]
I'm closing this issue. It does not make sense to run the farmerbot on ARM. If a user wants to he can go ahead and do it but releasing the farmerbot on ARM means we have to do the support for it too. It does not make sense to do that unless a lot of users are running the farmerbot on ARM and I don't think they do.

**Comment by scottyeager** [comment]
Actually, there is high demand for running farmerbot on ARM based devices. Check the download count for my ARM build:

![image](https://github.com/threefoldtech/farmerbot/assets/17682591/d3ef004f-6a74-4e03-8e80-9a0696d30fa2)

Versus the download count for the x64 build:

![image](https://github.com/threefoldtech/farmerbot/assets/17682591/0d8cab7e-95d8-4c52-91fd-430383f6d6d1)

It makes a lot of sense to use an ARM device like a Raspberry Pi for farmerbot, because they are low power and reliable. So far building for ARM has not required any dev specific support like code changes. 

The support team is happy to handle any questions that come up around install or management of the farmerbot that might be ARM specific, so I don't really see an issue there. That said, I couldn't find a single case in our support system of a farmer asking for help with farmerbot on ARM based hardware. I've helped a couple personally, but they are mostly self sufficient or get answers from other farmers in the public chat.

Anyway, I'm happy to keep building, releasing, and support images for ARM. Having this done with our automated build system and under a unified container repository would be convenient, but it's not necessary. Since maybe it wasn't clear from reading the issue so far, I'll just say finally that I originally opened this issue after a request from @robvanmieghem:

>Do create an issue on github so we can build the arm executables as part of the release process

**Comment by brandonpille** [comment]
They are not as reliable as actual servers and it is very important that the farmerbot is up and running all the time. If they are not up and running farmers will come to us saying the farmerbot isn't working and that they didn't get their tokens for the month. I want to avoid these issues.

Also why would you run it on a Raspberry Pi? You would never really run a web server on a Raspberry Pi. Or any other kind of server for that matter... It's not because we can do something that we should do it. 

I prefer to release on systems that we have properly tested on. We don't even have an ARM device at the office, we've never ran it on such a device before. I prefer to limit the amount of devices/systems we release for so that we are sure it is properly working on those devices/systems. The users are free to use an ARM device to run the farmerbot on but we should limit the support on that.

**Comment by scottyeager** [comment]
I'm not sure how you've concluded that a Raspberry Pi is not reliable. Actually a very popular use for them is web servers, both low traffic public internet servers as well as private home servers. They're also used as irrigation controllers, weather monitoring stations, digital signage drivers, 3d printer control units, and a variety of other tasks where reliability is a primary concern. They're even being used in commercial industrial [control and monitoring](https://en.wikipedia.org/wiki/Raspberry_Pi#Industrial_automation) applications.

Farmers can, and probably will, find much less reliable x64 based hardware to run their farmerbot on (I saw one example where the farmerbot appears to be running on an old laptop). In every case, it is their own responsibility to choose hardware that they feel is reliable enough for them and to take responsibility for any issues caused by their choice. Myself and the support team will handle any such situation that arise, regardless of what CPU architecture the binaries are compiled for.

As for testing, I have a Pi and I've also seen that @maxux was experimenting with running Zos on one a while back. What kind of tests would you need to see completed to feel that it has been properly tested?

**Comment by brandonpille** [comment]
Just leaving the farmerbot running on it for a while would be a good test

**Comment by robvanmieghem** [comment]
Pi's are indeed very reliable but I don't think that is where the discussion is about.

A lot of time already goes into support for the farmerbot on 1 platform, if PI's are an officially supported farmerbot platform, fixes, releases and support time will even increase while we already have a lot on our plate.

I do think that providing binaries in our github release flows is better than people having them from somewhere else.
All with a statement that ARM is beta and no support is provided off course.

**Comment by scottyeager** [comment]
For sure, I want to avoid placing any extra burden on the dev team here.

Since I've already created working Dockerfiles for the three containers that we release that are part of the farmerbot deployment, all that's really needed is some review and to add them into the workflows.

While myself and a number of farmers have tested the builds so far without any architecture specific issues, I can also commit to testing each new release personally.

What I'll do from here is work on creating pull requests to get the build files into the relevant repos. Then they can be reviewed an merged.

**Comment by robvanmieghem** [comment]
We do need to see if and how ghcr.io supports multi-arch container images
