### ISSUE TITLE
Farmerbot on testnet failed to wake up the nodes after powering them off

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/farmerbot#18]
### Description

After successfully completing my farmer bot setup on testnet farm `336` Nodes `248, 249, 250, 251` The nodes were successfully powered off but they were not able to get back up again. 

- I tried to fill node `251` to exceed the threshold so that another node could be powered on but when i checked from the chain its target was set to up but the state was still down.
- Another trial was that i edited the `config.md` file to set node `248` to never shut down but this also didn't work and the target was changed to up but the state was still down.

### Logs

- [config.md](https://gist.github.com/mohamedamer453/81e0d68aa1c344f9599514032775e827)
- [farmerbot.log](https://gist.github.com/mohamedamer453/6ea60b502de9de6cef7b733dcdc3a704)
- [docker compose logs](https://gist.github.com/mohamedamer453/dc271e0da3438cc27c5aa4f624b391d9)

**Comment by mohamedamer453** [comment]
Update

Currently checking the config and trying a fix with @brandonpille. will update the issue with any new info!

**Comment by mohamedamer453** [comment]
Update.

After multiple trials, restarts (both for the farmerbot and the nodes) with @brandonpille, the nodes were still not able wake up after they're powered off by the farmerbot.

As mentioned above the node that stays up in the farm sends the `wol` packets to the down nodes and their target is changed to up but they don't start and the state remains as down.

We've also tried to set change the power target directly from the chain and it's reflected correctly in the power target for each nodes however it still doesn't wake up the node.

The current issue is suspected to be with the `WOL` of the nodes itself

**Comment by brandonpille** [comment]
The problem is indeed the WOL from the nodes themselves. The nodes were used last week with the farmerbot on devnet so we expect them to work properly. The settings have not been modified and the nodes have not been powered off. We looked at the BIOS settings to see if everything is still well configured. The configuration seems fine altough we are not sure what settings should be set to enable WOL. The person who previously configured the nodes was not at the office yesterday so we will be asking him to take a second look later.

**Comment by mohamedamer453** [comment]
The issue with the `WOL` for the nodes was fixed today and i was able to observe and execute multiple tests on the mentioned farm.

Some of the scenarios that were tested on this farm to verify that everything is working fine:

- Starting the farmerbot and seeing 3/4 nodes power off since they didn't have any deployments.
- Observing the `periodic_wakeup` of the nodes. each node in the farm was powered on within 5 min intervals and after 30 mins each node was powered off again.
- Creating deployments with resources lower than the `wakeup_threshold` to test that another node shouldn't be powered on.
- Creating deployments with resources higher than the `wakeuo_threshold` to verify that another node will wake up once the farmerbot detects that this node is almost full.
- Verifying that nodes power off without any issue 30 mins after the contracts on it are deleted.
- Pinging farms from the weblets and grid3_client.

There are a couple of concerns about filtering nodes managed by the farmerbot from the weblets. discussed in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/78 & https://github.com/threefoldtech/tfgrid-sdk-ts/issues/76 other than that everything else went smoothly without any issues.

Thanks again @brandonpille for your troubleshooting and help with the testing process!
