### ISSUE TITLE
Periodic wakeup does not take into account hour change

### ISSUE THREAD

**Issue by brandonpille** [threefoldtecharchive/farmerbot#19]
The periodic wakeup happens every day at the same local time which results in a wakeup every 24 hours. It does not take into account the time change. So during the time change it will either be 23 hours or 25 hours. We should fix the 25 hour problem.

**Comment by ashraffouda** [comment]
code is here https://github.com/threefoldtech/farmerbot/pull/70  but farmer bot is kinda broken because of https://github.com/threefoldtech/farmerbot/issues/67#issuecomment-1790639954
