### ISSUE TITLE
Support for hex based TF Chain secrets

### ISSUE THREAD

**Issue by scottyeager** [threefoldtecharchive/farmerbot#20]
Many farms have been created with the TF Connect App, where the farmer only receives a hex based secret for the TF Chain account controlling the twin and the farm. It would be nice to support these farms in the `farmerbot`.

- [x] `rmb-rs` - [already](https://github.com/threefoldtech/rmb-rs/commit/00fdc4b8b6c10882a4c81f08244de1974008e964) supports this
- [x] `grid3_client_ts` - feature request created [here](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/8)

With support in both, it would just be a matter of adding some logic to detect which form is provided and invoke the services appropriately.

**Comment by scottyeager** [comment]
It actually already works, just by subbing the hex secret into the `MNEMONIC` field in the `.env` file. All that's left, in that case is to add a note in the documentation that a "mnemonic or hex secret" is accepted.

**Comment by brandonpille** [comment]
Ok. I will update the documentation. I'll rename the MNEMONIC field to SECRET, I think it will be more appropriate.
