### ISSUE TITLE
how are dedicated nodes power managed?

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/farmerbot#27]

**Comment by brandonpille** [comment]
Like any other node. Or do you mean nodes that have a rent contract on them?

**Comment by xmonader** [comment]
When I rent a full node indeed, It should be excluded from the calculations of the farmerbot's capacity planning and its power management imo need to be handled in a different way if not already

**Comment by brandonpille** [comment]
Why should it be execluded from the capacity planning? And how should the power management look like?

**Comment by xmonader** [comment]
As this rented node isn't really usable by anyone other than the renter 

- Any planning request from users side (who aren't renting the node) will either return that node, or will need to power on other nodes (because it depended on the capacity of a dedicated node that wasn't going to be used to fulfill that request anyways)
- The threshold calculations to power on/off other offline nodes as the rented nodes aren't really usable by others


The way I see it for the power management: we need to have a decision for dedicated nodes, either be always powered on or not -if the cost doesn't justify the bill-, but even if it was going to be powered off to save energy, It should be isolated from the shared nodes.

**Comment by brandonpille** [comment]
When there is a rent contract it will keep the node up and it will be marked as "used" so it will not be returned to other requests.
