### ISSUE TITLE
Send batch messages when pinging the nodes

### ISSUE THREAD

**Issue by scottyeager** [threefoldtecharchive/farmerbot#30]
From @scottyeager: "We've had several reports from farmers, including my own experience with testing, that `rmb-peer` sometimes reports that it has `received reply of an expired message`. I wonder if a five second timeout for node replies might be too short?"

The issue could indeed be that 5 seconds is not enough time to wait for a reply. Increasing the timeout will work but it would not be a good idea. The pings are send sequentially so increasing the timeout will increase the time to get the status of the nodes. Instead we could send batch messages:

1. We put all messages (for all nodes) in the rmb queue: _msgbus.system.local_
2. We use blpop with multiple queues which will result in redis waiting till one of the queues has a message in it. The timeout can be 5 or 10 seconds. Lets experiment with both timeouts. Although 5 seconds was maybe not enough time we will be sending batch messages thus we will be gaining some time.
3. Based on the queue we execute the corresponding code. blpop only returns one message (the first queue that has a message in it). So after that we will have to execute blpop again to get the other nodes' responses. I think executing it N (amount of batch calls) times (each time providing the different queues) makes sense. This means that each node will have N*5 seconds to respond. Also notice that the total time to contact all nodes (in batch mode) will not extend the current time to call all nodes sequentially.
4. The nodes that don't respond within that time frame are considered offline.

**Comment by brandonpille** [comment]
Can you show me the message? Do you know if it is a message from a node? Because waiting longer then 5 seconds results in more wait time. I could also send batch messages and brpop from multiple queues. That will require some change in the code. This could be a good improvement though!

**Comment by scottyeager** [comment]
Here's an example output sent from a farmer:

```
2023-04-25T20:56:43.102Z WARN  [rmb::peer] received reply of an expired message
```

I was also thinking that batching the pings with a longer expiration time would be a good solution :+1:

**Comment by muhamadazmy** [comment]
What is the expiration value are u using ? might be too short ?

**Comment by muhamadazmy** [comment]
Also there is no need to send pings sequentially, rmb can handle multiple parallel requests normally. So you can simply send a ping to 'fan out' to multiple nodes with, then wait on all responses to arrive. Whenever a node does not respond in the requested window can be considered unreachable

**Comment by muhamadazmy** [comment]
in RMB docs here 
https://github.com/threefoldtech/rmb-rs/tree/main/docs#output-requests

You can see you can specify all destinations in a single ping message. so the bot can simply ask all farm nodes at once to send him their state. Whatever node sends back a response will be available on the response queue.

It's completely up to the farmerbot to decide how to make the calls
