### ISSUE TITLE
Automatic .env and config.md Script for Farmerbot (.v, .sh and .py)

### ISSUE THREAD

**Issue by mik-tf** [threefoldtecharchive/farmerbot#33]
# Automatic .env and config.md Script for Farmerbot (.v, .sh and .py)

Here is a script that generates the .env and config.md files for the Farmerbot.

This is a first draft. It should write the files properly. I set this as an issue to get feedback from the community and the dev team and then adjust accordingly.

Every input asked are dealt in terms of potential input errors, except for the HEX or seed phrase to give room for the two formats.

The 12 hour format is required to simplify the script.

***

## Link to the Script

Follow the steps on this repo:
https://github.com/Mik-TF/farmerbot-script

***

If Threefold appreciates this script, we could add it on the Farmerbot guide and also on this repository (threefoldtech/farmerbot)

***

Feedback and questions are welcome.

UPDATE: The script is now available in both Python and Bash, as discussed in this issue.

**Comment by brandonpille** [comment]
Nice work! Although a bash script might not be the best solution here... For future development purposes I mean. Maybe I can do it in V or in Python and release it together with the farmerbot?

**Comment by mik-tf** [comment]
@brandonpille 

Great! Thanks for the proposition Brandon. I think it would be great if you want to tune this into a V or Python version.

That's exactly what I had in mind: build a script that works and get your feedback to see how to go forward.

Let me know if I can be of any help.

**Comment by mik-tf** [comment]
Edit: I changed the name from nodes.md to config.md for convention purpose (detail).

**Comment by mik-tf** [comment]
@brandonpille 

You can have a look here: https://github.com/Mik-TF/farmerbot-script/blob/main/farmerbot_script.py
I did the necessary changes to have it in python, as requested.

Let me know what you think!

Clearly the code could be shorter, with functions et al. But it gets the job done!

**Comment by brandonpille** [comment]
It's a bit messy indeed. Maybe I can give a few pointers:
- It is preferred to use the main function when creating tools in python: https://realpython.com/python-main-function/#a-basic-python-main
- It is indeed a better idea to put the code in separate functions
One more thing. The users will have to install Python in order to run this... Maybe an executable build with V would have been better, no?

**Comment by mik-tf** [comment]
OK thanks for the feedback.

I agree using a main function and different functions for the code in Python would be 100% better.
Also, it's a good point that an executable build with V instead of Python would be better.

If you have a clear idea on what is needed to get it in V with a better flow, let me know if you want to go ahead and convert either the bash or python to V yourself.

Otherwise, I can do the conversion to V myself. But it would surely take some more time.

Thanks again for all the great feedback and help on this.

**Comment by brandonpille** [comment]
You can go ahead with the conversion. Did you ever write V code? If no I can help you. We can have a quick call if you like.

**Comment by mik-tf** [comment]
Thank you Brandon for the help. I did try some V before and did check the documentation a little. It looks very well designed. I know it can be learned over a weekend, so there's no excuse! I'll go through the [documentation](https://github.com/vlang/v/blob/master/doc/docs.md) and [vlib](https://modules.vlang.io/).

I will have a try and let you know if I get stuck or need help at some point.

I'll start by converting the python and/or bash to Vlang, and then "clean" the code (setting the main and other functions).

**Comment by mik-tf** [comment]
The Vlang version is now done with the necessary steps to install and run: https://github.com/Mik-TF/farmerbot-script

The script itself: https://github.com/Mik-TF/farmerbot-script/blob/main/farmerbot_script.v

I can either do a PR now, or get feedback and update the VLang version.

Should I publish also the bash and python? Or just the Vlang for the pull request in the farmerbot repo?

Should I do a branch and put the script in this subrepo?: https://github.com/threefoldtech/farmerbot/tree/development/scripts

Thanks!

**Comment by mik-tf** [comment]
There is a new version that queries grid proxy when possible:

https://github.com/Mik-TF/farmerbot-script/blob/main/farmerbot_script_gridproxy.v

The user only needs to give the node ID for the program to query:
* farm ID
* public IP in the farm
* public config of the node
* dedicated status of the node
* certification status of the node

**Comment by brandonpille** [comment]
> The Vlang version is now done with the necessary steps to install and run: https://github.com/Mik-TF/farmerbot-script
> 
> The script itself: https://github.com/Mik-TF/farmerbot-script/blob/main/farmerbot_script.v
> 
> I can either do a PR now, or get feedback and update the VLang version.
> 
> Should I publish also the bash and python? Or just the Vlang for the pull request in the farmerbot repo?
> 
> Should I do a branch and put the script in this subrepo?: https://github.com/threefoldtech/farmerbot/tree/development/scripts
> 
> Thanks!

Hi. Thanks, yes you can create a branch, put it in the scripts folder and then open up a PR. I'll review it.

**Comment by brandonpille** [comment]
> 

What exactly is the purpose of that script?

**Comment by mik-tf** [comment]
OK I will soon make a PR with both versions: the one that queries gridproxy and the other than ask all the questions for the user to add manually.

The purpose: with this script, farmers can create very quickly the .env and config.md files.
Also with the version that queries gridproxy, they only need to enter the node IDs to get farm ID, public IP of the farm, public config, dedicated, certification status of the node.

A lot of farmers asked for a smoother way to install the farmerbot. That's in this spirit.

**Comment by mik-tf** [comment]
@brandonpille 

Here is a new version that will show more clearly the purpose:

https://github.com/Mik-TF/farmerbot-script/blob/main/fbot_README.md

By following those steps, the farmer can deploy the farmerbot very quickly.

* create the folder and files structure
* download and run .yaml farmerbot
