### ISSUE TITLE
Error in Powermanager

### ISSUE THREAD

**Issue by mik-tf** [threefoldtecharchive/farmerbot#34]
A farmer had the following error:

[ERROR] [POWERMANAGER] Job to power off node xxxx failed: Failed to apply setNodePower in module tfgridModule with xxxx,false due to error: UnauthorizedToChangePowerTarget

I think it's a first.

Here is the original telegram message: https://t.me/threefoldtesting/12454

***

If there is a fix I will relay the information.

**Comment by brandonpille** [comment]
Only the twin of the farm is able to set the node power on chain (setNodePower). This means you provided a wrong mnemonic.
