### ISSUE TITLE
Farmerbot doesn't detect nodes as up after relay outage

### ISSUE THREAD

**Issue by scottyeager** [threefoldtecharchive/farmerbot#39]
After the relay was unreachable today, some farmers using farmerbot reported that the bot failed to detect their nodes as up. I'm guessing that this is due to `rmb-peer` not reconnecting after the relay came back up, but I'm not sure.

A restart of the bot fixed this situation, but it would be nice to recover automatically.

**Comment by brandonpille** [comment]
Yes it is the rmb-peer that was not reconnecting. But that has been fixed with the latest version of rmb-peer which we are already using in the farmerbot.
