### ISSUE TITLE
Node not turning on with new version of FB

### ISSUE THREAD

**Issue by amandacaster** [threefoldtecharchive/farmerbot#49]
Users say that their nodes are not booting on ( ZeroOS gets errors and a blank screen) after updating to farmerbot's latest version. 
![14BBB29A-BA4C-4811-A533-866FDC82D5C9_1_201_a](https://github.com/threefoldtech/farmerbot/assets/88147124/9336038f-d2c8-4843-bb70-6903f6721510)
![IMG_0435](https://github.com/threefoldtech/farmerbot/assets/88147124/080ddefa-a4e7-466d-8b99-4b45a304aba2)
![6963FDF4-74C4-4B9A-8F3C-01287AA927EC_1_201_a](https://github.com/threefoldtech/farmerbot/ass
![389809A8-3496-453F-879A-C55AB99C3ADE_1_201_a](https://github.com/threefoldtech/farmerbot/assets/88147124/00eb0158-356e-4415-b92b-11236461adcf)
ets/88147124/c28a7989-4084-4169-b5d5-8511508e7fbe)
![4500D1C3-2522-419E-BB0A-B4ED0D6AFFE5_1_201_a](https://github.com/threefoldtech/farmerbot/assets/88147124/a7990f0c-4f91-461e-93e3-d154dfd0e38a)

**Comment by amandacaster** [comment]
Related issue on Zos repo [#2001](https://github.com/threefoldtech/zos/issues/2001)

**Comment by muhamadazmy** [comment]
Can we also see the logs from `Alt+F2`

**Comment by amandacaster** [comment]
> Can we also see the logs from `Alt+F2`

I have already requested them, waiting to hear from the user.

**Comment by amandacaster** [comment]
[farmerbot (2).log](https://github.com/threefoldtech/farmerbot/files/12015556/farmerbot.2.log) 

[nodes (1).md](https://github.com/threefoldtech/farmerbot/files/12015595/nodes.1.md)

**Comment by amandacaster** [comment]
Based on the reply from Brandon on the [Forum post ](https://forum.threefold.io/t/new-release-farmerbot/4014/2) have let the user know and closing this for now.
