### ISSUE TITLE
"Error while calling set_node_power" after 0.2.0 update

### ISSUE THREAD

**Issue by scottyeager** [threefoldtecharchive/farmerbot#52]
Since updating to the new `docker-compose.yaml` file for farmerbot v0.2.0, farmers have reported seeing the following error:

```
Job to power on node X failed: Error while calling set_node_power: Cannot read properties of undefined (reading 'toJSON')
```

The apparent fix of moving from `grid_http_server:2.1.0-rc1`  to `grid_http_server:2.1.0-rc2` did not work for most farmers who tried it. I was able to reproduce the error on `rc2`.

What did work for me is using version `2.0.0`:

```
grid3_client:
    image: ghcr.io/threefoldtech/grid_http_server:2.0.0
...
```

**Comment by scottyeager** [comment]
As an update on this, my testing above was done with testnet.

@Mik-TF also tested on mainnet with `grid_http_server:2.0.0` and it resolved the issue for him.

**Comment by brandonpille** [comment]
Ahmed Hanay told me that 2.0.0 is the version to use for main, test and qa net and 2.1.0-rc2 is the version to use for devnet
