### ISSUE TITLE
grid3_client error with new release

### ISSUE THREAD

**Issue by mik-tf** [threefoldtecharchive/farmerbot#55]
Nelson and Jan Reyes on the TG Farmers chat are getting an error when deploying the Farmerbot with the new release ([link](https://t.me/threefoldfarmers/63471)).

There is an open ticket on the TF Support team about this.

![telegram-cloud-photo-size-1-5019637388640627687-x](https://github.com/threefoldtech/farmerbot/assets/77026219/d9f1e884-3c0a-4835-bd85-6be309fdc978)

They will re-try the deployment on their side and see if the issue persists.

**Comment by brandonpille** [comment]
I would need to get the logs of the container too. What you can do is start the service without the -d flag:
```
docker compose up
```
This will redirect the output to your console and then you will be able to see it. Show me the result of that please.

**Comment by TullysInc** [comment]
https://github.com/threefoldtech/tf_support/issues/568

**Comment by brandonpille** [comment]
> [threefoldtech/tf_support#568](https://github.com/threefoldtech/tf_support/issues/568)

This looks like a different issue

**Comment by mik-tf** [comment]
Thanks Brandon. I asked the farmers to send the logs [here](https://t.me/threefoldfarmers/63582). I'll post here when they share the logs.

If it isn't possible (e.g. they started another container and delete the logs) I will also let you know.

**Comment by mik-tf** [comment]
Here is the log

```
farmerbot_docker-grid3_client-1  | yarn run v1.22.19
farmerbot_docker-grid3_client-1  | warning package.json: No license field
farmerbot_docker-grid3_client-1  | $ /node_modules/.bin/grid_http_server -c /root/config.json
farmerbot_docker-grid3_client-1  | 2023-07-18 21:14:51        API/INIT: RPC methods not decorated: transaction_unstable_submitAndWatch, transaction_unstable_unwatch
farmerbot_docker-grid3_client-1  | 2023-07-18 21:14:51        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/2 (1 known)
farmerbot_docker-grid3_client-1  | Error: Invalid twin id. Twin id must be postive integer
farmerbot_docker-grid3_client-1  |     at Twins.get (/node_modules/@threefold/tfchain_client/dist/node/twins.js:22:19)
farmerbot_docker-grid3_client-1  |     at descriptor.value (/node_modules/@threefold/tfchain_client/dist/node/utils.js:12:31)
farmerbot_docker-grid3_client-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
farmerbot_docker-grid3_client-1  |     at async Client.connect (/node_modules/@threefold/rmb_direct_client/dist/node/client.js:106:25)
farmerbot_docker-grid3_client-1  |     at async GridClient.connect (/node_modules/@threefold/grid_client/dist/node/client.js:112:17)
farmerbot_docker-grid3_client-1  |     at async HttpServer.register (/node_modules/@threefold/grid_http_server/dist/server.js:64:9)
farmerbot_docker-grid3_client-1  | Error: Unable to establish a connection with the RMB server. Please check your internet connection and try again. If the problem persists, please contact our support.
farmerbot_docker-grid3_client-1  |     at GridClient.connect (/node_modules/@threefold/grid_client/dist/node/client.js:115:23)
farmerbot_docker-grid3_client-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
farmerbot_docker-grid3_client-1  |     at async HttpServer.register (/node_modules/@threefold/grid_http_server/dist/server.js:64:9)
```

The farmer (Nelson) could fix it finally. It seems it was just a wrong seedphrase.

I'll write up more info here in case we get a clearer understanding. But the issue is fixed in all cases. Closing this.
