### ISSUE TITLE
Installing dependencies in Docker and CI should happen using versions

### ISSUE THREAD

**Issue by brandonpille** [threefoldtecharchive/farmerbot#6]
We currently have 2 V dependencies: baobab and crystallib. Both repositories are cloned and then installed in order to build the farmerbot (both in CI and in Dockerfile). We should start using versions of those dependencies instead. But that will only be possible once these two tickets are done: https://github.com/freeflowuniverse/baobab/issues/8 and https://github.com/freeflowuniverse/crystallib/issues/124.

**Comment by ashraffouda** [comment]
blocked because of https://github.com/threefoldtech/farmerbot/issues/67#issuecomment-1790639954
