### ISSUE TITLE
farmerbot log report node as certified 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/farmerbot#7]
Why is the farmerbot.log says that my node is certified while it's not. 
![image](https://user-images.githubusercontent.com/109473873/225297557-7af51a8a-084d-437b-bdf1-2bd5b61aa57e.png)

markdown file
![image](https://user-images.githubusercontent.com/109473873/225297670-31ff3ece-e6c0-4e85-af5b-a03925b69a5d.png)
https://gridproxy.dev.grid.tf/nodes/69
![image](https://user-images.githubusercontent.com/109473873/225297950-4302dd14-fa90-4620-b21c-d2899823f87d.png)

**Comment by brandonpille** [comment]
Can I see your configuration file? The .md file. The only way that certified is set to true is because of the configuration file. Did you  set certified to yes in the configuration file?

**Comment by brandonpille** [comment]
Hi. I see what is wrong here. Could you set the value to false please? Or you can just not add the configuration argument. That will be the same result.

**Comment by brandonpille** [comment]
I modified the code to also recognize "no" in the arguments. Can you please use the new docker-compose file from https://github.com/threefoldtech/farmerbot/blob/development/docker-compose.yaml and try again?

**Comment by A-Harby** [comment]
Verified.
So I deleted the log file and run `docker compose rm -f -s && docker compose up -d`, and it was fixed
![image](https://user-images.githubusercontent.com/109473873/225614676-1c6290d9-4442-4cda-b887-77caa5929a5c.png)
