### ISSUE TITLE
High cpu usage when idle

### ISSUE THREAD

**Issue by scottyeager** [threefoldtecharchive/farmerbot#9]
I've noticed that when the farmer bot has nothing to do, it uses a lot of cpu:

![image](https://user-images.githubusercontent.com/17682591/225773250-dbe97e5e-0b0c-4b94-a204-2f6440d7c19e.png)

This happens whenever the bot has finished performing any necessary actions, or if it simply isn't given any nodes to manage.

Meanwhile, I see `get_my_twin_id` running over and over again in the logs. I don't understand this behavior, since a twin is permanently associated with an account, as far as I know.

**Comment by brandonpille** [comment]
I'll look into it. The get_my_twin_id is used to see if the grid3 client is alive. That could be the reason why it is using a lot of cpu.

**Comment by brandonpille** [comment]
Alright I found the issue. It comes from baobab. Baobab is constantly looking into redis queues for jobs to execute (in a for loop). Adding 100ms of sleep in the loop reduces the CPU usage to 0.6%. Would that be acceptable?

**Comment by brandonpille** [comment]
I created v0.1.0-rc12. Please check it out and let me know the cpu usage.

**Comment by scottyeager** [comment]
This helped, but I still think the approach can be improved: https://github.com/freeflowuniverse/baobab/issues/13

**Comment by despiegk** [comment]
its very normal, in no language we should do an unlimited loop to a network
service,
if the network service is local you will burn through lots of CPU

the faster the language the more CPU will be used
